services:
  microapp.usersservice:
    image: microapp.usersservice
    build:
      context: .
      dockerfile: MicroApp.UsersService/Dockerfile

  cardsservice:
    image: cardsservice
    build:
      context: .
      dockerfile: CardsService/Dockerfile

